name: Deploy Lambda Entry API function to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/entry/**'
      - '.github/workflows/deploy_entry_lambda.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  LAMBDA_FUNCTION_NAME: ailumni-api

jobs:
  build-and-deploy:
    name: Build and Deploy API Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies and build
        working-directory: ./lambda/entries
        run: |
          npm ci
          npm run build

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --zip-file fileb://lambda/entries/entries.zip --region ${{ env.AWS_REGION }}